const assert = require('node:assert/strict');
const backup = require('../static/backup.js');
function storage() {
  const data = new Map();
  return {getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};
}
const source = storage();
source.setItem('quiz_deepseek_cfg_v1',JSON.stringify({key:'secret'}));
source.setItem('quiz_bank_stats_v1',JSON.stringify({bank:{'001':{wrong:3,lastAt:20}}}));
source.setItem('quiz_question_seen_v1',JSON.stringify({bank:{'001':1}}));
source.setItem('quiz_ai_analysis_text_v2',JSON.stringify({bank:{'001':'new'}}));
source.setItem('quiz_structured_analysis_v2',JSON.stringify({bank:{'001':{version:2,study_type:'memory',reason:'术语',explanation:'定义',memory_tip:'提示',fingerprint:'test',needs_review:false}}}));
const exported = backup.capture(source);
exported.data.quiz_sessions_v1 = {bank:{ids:['001','002'],mode:'unseen',category:'',updatedAt:100}};
assert(!JSON.stringify(exported).includes('secret'));
const target = storage();
target.setItem('quiz_bank_stats_v1',JSON.stringify({bank:{'001':{wrong:2,lastAt:30}}}));
target.setItem('quiz_ai_analysis_text_v2',JSON.stringify({bank:{'001':'keep'}}));
backup.restore(target,JSON.parse(JSON.stringify(exported)));
assert.deepEqual(JSON.parse(target.getItem('quiz_sessions_v1')).bank.ids,['001','002']);
const oldBackup=JSON.parse(JSON.stringify(exported));
delete oldBackup.data.quiz_sessions_v1;
assert.deepEqual(backup.validate(oldBackup).data.quiz_sessions_v1,{});
assert.deepEqual(JSON.parse(target.getItem('quiz_bank_stats_v1')).bank['001'],{wrong:3,lastAt:30});
assert.equal(JSON.parse(target.getItem('quiz_ai_analysis_text_v2')).bank['001'],'keep');
const once = backup.capture(target);
backup.restore(target,exported);
assert.deepEqual(backup.capture(target).data,once.data);
assert.throws(()=>backup.validate({...exported,version:99}));
assert.throws(()=>backup.validate({...exported,data:{...exported.data,quiz_deepseek_cfg_v1:{}}}));
const polluted = JSON.parse(JSON.stringify(exported));
polluted.data.quiz_question_seen_v1 = JSON.parse('{"__proto__":{"x":1}}');
assert.throws(()=>backup.validate(polluted));
const full = storage();
const write = full.setItem;
let attempts = 0;
full.setItem=(k,v)=>{if(++attempts===2)throw new Error('Quota');write(k,v);};
assert.throws(()=>backup.restore(full,exported),/已恢复/);
assert.deepEqual(backup.capture(full).data,backup.capture(storage()).data);
console.log('PASS: round trip, credentials excluded, merge, idempotence, validation, rollback');
